//user
export const LOGIN_USER = "LOGIN_USER"
export const REGISTER_USER = "REGISTER_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const AUTH_USER = "AUTH_USER"
export const GET_MY_PRODUCTS = "GET_MY_PRODUCTS"
export const UPDATE_PROFILE = "UPDATE_PROFILE"

export const UPDATE_LIKE = "UPDATE_LIKE"
export const UPDATE_LIKE_SUCCESS = "UPDATE_LIKE_SUCCESS"
export const UPDATE_LIKE_FAILURE = "UPDATE_LIKE_FAILURE"

export const UPDATE_TAKE = "UPDATE_TAKE"
export const UPDATE_TAKE_SUCCESS = "UPDATE_TAKE_SUCCESS"
export const UPDATE_TAKE_FAILURE = "UPDATE_TAKE_FAILURE"

//product
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"

export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE"
