//user
export const LOGIN_USER = "LOGIN_USER"
export const REGISTER_USER = "REGISTER_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const AUTH_USER = "AUTH_USER"
export const UPDATE_PROFILE = "UPDATE_PROFILE"

export const UPDATE_LIKE = "UPDATE_LIKE"
export const UPDATE_USER_TAKE = "UPDATE_USER_TAKE"

//product
export const PRODUCTS = "products"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"

export const GET_PRODUCTS_MORE = "GET_PRODUCTS_MORE"

export const PRODUCT = "product"
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE"

export const UPDATE_PRODUCT_LIKE = "UPDATE_PRODUCT_LIKE"
export const UPDATE_PRODUCT_LIKE_SUCCESS = "UPDATE_PRODUCT_LIKE_SUCCESS"
export const UPDATE_PRODUCT_LIKE_FAILURE = "UPDATE_PRODUCT_LIKE_FAILURE"

export const REP_PRODUCT = "repProduct"
export const GET_REP_PRODUCT = "GET_REP_PRODUCT"
export const GET_REP_PRODUCT_SUCCESS = "GET_REP_PRODUCT_SUCCESS"
export const GET_REP_PRODUCT_FAILURE = "GET_REP_PRODUCT_FAILURE"
