export const LOGIN_USER = "LOGIN_USER"
export const REGISTER_USER = "REGISTER_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const AUTH_USER = "AUTH_USER"
export const ADD_TAKE = "ADD_TAKE"
export const ADD_LIKE = "ADD_LIKE"
export const REMOVE_TAKE = "REMOVE_TAKE"
export const UPLOAD_AVATAR = "UPLOAD_AVATAR"